Benchmark:
  path: ./Benchmark/BFCL/BFCL_v4_sql.jsonl
  type: single-agent multi-round
  per_task_tools: true  
  start_idx: 1
  end_idx: 1


Toolkit:
  path:  ./Toolkit/BFCL/generated_tools/BFCL_v4_sql
  generated_dir: ./Toolkit/BFCL/generated_tools

Model:
  provider: openai-server
  parameters:
    temperature: 0.0
    max_tokens: 4096
    timeout: 60
  providers:
    openai-server:
      model_id: gpt-4o-mini
      api_base: https://api.openai.com/v1
      api_key: "your-api-key-here"
      temperature: 0.0

Environment:
  path: ./Environment/BFCL/exports
  type: per-task

Agent:
  type: single-agent multi-round
  agent_dir: ./Agent/BFCL
  agent_type: ToolCallingAgent
  stream_outputs: false
  planning_interval: -1
  max_tool_threads: 1
  fill_with_all_tools: false

Output:
  log_dir: ./Results/logs/BFCL/BFCL_v4_sql
  save_dir: ./Results/outputs/BFCL/BFCL_v4_sql

Evaluation:
  enabled: false
